name: Convert RST to ADOC

on:
  push:
    paths:
      - 'controller-source/**'
    branches:
      - 'master'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=FILES::$(find . -name '*.rst' -print)"

      - uses: docker://pandoc/core:latest
        with:
          args: >
            -f rst
            -t asciidoc ${{ steps.files_list.outputs.FILES }}
            -o ${{ steps.files_list.outputs.FILES }}.adoc

      - name: show me
        run: |
          cd controller-source
          ls -1

      - uses: actions/upload-artifact@master
        with:
          name: output
          path: controller-adoc
