name: Convert RST to ADOC

on:
  push:
    paths:
      - 'controller-source/**'
    branches:
      - 'master'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: create output directories
        id: files_list
        run: |
          for d in */; do
            mkdir -p output/$d
          done
      - name: show me
        run: |
          ls -1
      - name: convert rst to adoc
        run: |
          find . -name "*.rst*" | while read i; do pandoc -f rst -t asciidoc "$i" -o output/"${i%.*}.adoc"; done

      - uses: actions/upload-artifact@master
        with:
          name: output
          path: controller-adoc
