name: Convert RST to ADOC

on:
  push:
    paths:
      - 'controller-source/**'
    branches:
      - 'master'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest-ubuntu
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: convert rst to adoc
        run: |
          cd controller-source
          find . -name "*.rst*" | while read i; do pandoc -f rst -t asciidoc "$i" -o "${i%.*}.adoc"; done

      - name: install git
        run: apt-get -y update && apt-get -y install git

      - name: clone infinispan.github.io
        uses: actions/checkout@v2
        with:
          repository: oraNod/red-hat-ansible-automation-platform-documentation
          ref: master
          path: red-hat-ansible-automation-platform-documentation

      - name: move files
        run: |
          cd controller-source
          find . -name '*.adoc' -exec mv {} ../red-hat-ansible-automation-platform-documentation/controller-adoc \;

      - name: Commit files
        run: |
          cd red-hat-ansible-automation-platform-documentation
          git commit -m "Synchronize converted Controller docs" -a
          git config --global user.email "dnaro@redhat.com"
          git config --global user.name "oraNod"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORANOD }}
          branch: master
