name: Convert RST to ADOC

on:
  push:
    paths:
      - 'controller-source/**'
    branches:
      - 'master'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest-ubuntu
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: show me
        run: |
          ls -1
      - name: convert rst to adoc
        run: |
          cd controller-source
          find . -name "*.rst*" | while read i; do pandoc -f rst -t asciidoc "$i" -o "${i%.*}.adoc"; done
      - name: move files
        run: |
          cd controller-source
          find . -name '*.adoc' -exec mv {} ../controller-adoc \;

      - name: Clone infinispan.github.io
        uses: actions/checkout@master
        with:
          repository: oraNod/red-hat-ansible-automation-platform-documentation
          ref: master
          path: red-hat-ansible-automation-platform-documentation

      - name: Copy docs to repo
        run: |
          cp -r controller-adoc red-hat-ansible-automation-platform-documentation

      - name: Show me
        run: |
          cd red-hat-ansible-automation-platform-documentation/controller-adoc
          ls controllerapi/source/

      - name: Commit files
        run: |
          cd red-hat-ansible-automation-platform-documentation
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git config --global user.name "docs-bot"
          git config --global user.email "docs-bot@redhat.com"
          git add . --all
          git commit -m "Synchronize converted Controller docs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
