name: Convert RST to ADOC

on:
  push:
    paths:
      - 'controller-source/**'
    branches:
      - 'master'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:latest
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: show me
        run: |
          ls -1
      - name: convert rst to adoc
        run: |
          cd controller-source
          find . -name "*.rst*" | while read i; do pandoc -f rst -t asciidoc "$i" -o "${i%.*}.adoc"; done
      - name: move files
        run: |
          cd controller-source
          find . -name '*.adoc' -exec mv {} ../controller-adoc \;
      - name: push converted asciidoc
        run: |
          cd controller-adoc

          git config --global user.name "docs-bot"
          git config --global user.email "docs-bot@redhat.com"

          git add -A
          git commit -m "Synchronize converted Controller docs"
          git push

      - uses: actions/upload-artifact@master
        with:
          name: output
          path: controller-adoc
