name: Convert RST to ADOC

on:
  push:
    paths:
      - 'controller-source/**'
    branches:
      - 'master'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=FILES::$(printf '"%s" ' *.rst)"

      - name: show me
        run: |
          echo ${{ steps.files_list.outputs.FILES }}

      - uses: docker://pandoc/core:latest
        run: |
          cd controller-source
          mkdir converted-asciidoc
          find . -name "*.rst*" | while read i; do pandoc -f rst -t asciidoc "$i" -o "${i%.*}.adoc"; done
          find . -name '*.adoc' -exec mv {} ./converted-asciidoc \;

      - name: show me
        run: |
          cd controller-source
          ls -1

      - uses: actions/upload-artifact@master
        with:
          name: output
          path: controller-adoc
